# Generated by Django 4.2.3 on 2023-08-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genero',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='edad',
        ),
    ]
