# Generated by Django 4.2.3 on 2023-08-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authmanager', '0002_rename_genero_user_password_remove_user_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imagen',
        ),
    ]
