# Generated by Django 4.2.3 on 2023-08-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanager', '0003_remove_user_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creador',
            field=models.BooleanField(default=False),
        ),
    ]
