# Generated by Django 4.2.3 on 2023-08-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanager', '0004_user_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creador',
            field=models.BooleanField(),
        ),
    ]
