# Generated by Django 4.2.3 on 2023-08-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanager', '0005_alter_user_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(default='static/uploads/users/default.png', upload_to='static/uploads/users'),
        ),
    ]
