# Generated by Django 4.2.3 on 2023-08-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authmanager', '0006_user_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
