# Generated by Django 4.2.3 on 2023-08-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_estudiante_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
