# Generated by Django 4.2.3 on 2023-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviews_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='juego',
            field=models.CharField(choices=[('NADA', 'Selecciona un Juego'), ('MINECRAFT', 'Minecraft'), ('LOL', 'League of Legends'), ('CSGO', 'Counter Strike Global Ofensive'), ('TERRARIA', 'Terraria'), ('VALORANT', 'Valorant'), ('GTAV', 'Grand Theft Auto V'), ('PHASMOPHOBIA', 'Phasmophobia')], default='NADA', max_length=50),
        ),
    ]
