# Generated by Django 4.2.3 on 2023-08-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_reviews_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='creador',
            field=models.CharField(default='{{user.username}}', max_length=300),
        ),
    ]
