# Generated by Django 4.2.3 on 2023-08-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_reviews_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(max_length=4000),
        ),
    ]
