# Generated by Django 4.2.3 on 2023-08-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_reviews_descripcion_alter_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
