# Generated by Django 4.2.3 on 2023-08-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_reviews_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
