# Generated by Django 4.2.3 on 2023-09-02 19:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_reviews_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
