# Generated by Django 4.2.3 on 2023-09-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
