# Generated by Django 4.2.3 on 2023-09-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_reviews_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='fecha',
            field=models.DateField(),
        ),
    ]
