# Generated by Django 4.2.3 on 2023-09-02 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_alter_reviews_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='fecha',
            field=models.DateField(verbose_name=datetime.date),
        ),
    ]
