# Generated by Django 4.2.3 on 2023-09-04 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_alter_reviews_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='fecha',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
    ]
