# Generated by Django 4.2.3 on 2023-09-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_alter_reviews_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='fecha',
            field=models.CharField(default='2023/09/03', max_length=200),
        ),
    ]
