# Generated by Django 4.2.3 on 2023-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_options_games_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='imagen',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
