# Generated by Django 4.2.3 on 2023-08-12 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=270),
            preserve_default=False,
        ),
    ]
