# Generated by Django 4.2.3 on 2023-08-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_games_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['nombre'], 'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
    ]
