# Generated by Django 4.2.3 on 2023-08-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_games_juego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='imagen',
        ),
    ]
